<template><h2 id="新建网站流程及思路" tabindex="-1"><a class="header-anchor" href="#新建网站流程及思路" aria-hidden="true">#</a> 新建网站流程及思路</h2>
<ol>
<li>
<p>学习vuepress</p>
<blockquote>
<p>基于vuePress做个人网站，记录平时遇到的问题和建站思路</p>
</blockquote>
</li>
<li>
<p>编写vue项目</p>
<blockquote>
<p>学习vue和elementPlus，编写动态网页，试着开发一些前端小游戏</p>
</blockquote>
</li>
<li>
<p>编写后端代码</p>
<blockquote>
<p>后端主要使用Spring-boot-plus开发，做业务数据处理，增强对框架、java代码、架构的理解。</p>
</blockquote>
</li>
<li>
<p>服务器</p>
<blockquote>
<p>购买服务器，搭建代码自动化部署</p>
</blockquote>
</li>
</ol>
</template>
